@startuml
!include D:\uml\C4-PlantUML\C4_Container.puml
LAYOUT_WITH_LEGEND()
LAYOUT_AS_SKETCH()
Person(user, "用戶")

System_Boundary(item, "商品相關"){
    System(itemCenter, "商品中心", "")
    System(priceCenter, "價格中心", "")
    System(InventoryCenter,"銷售庫存111", "")
}

System_Boundary(messageCenter, "消息中心"){
    System(message, "短信", "")
    System(wechat, "微信", "")
    System(email, "邮件", "")
    System(ali, "阿里", "")
    System(ali1, "阿里", "")
}

System_Ext(orderPlatform, "訂單平臺")
System_Ext(wmsStock,"wms庫存")
System_Ext(buy,"導購平臺")

Rel(orderPlatform,message,"推送消息")

Rel(wmsStock, InventoryCenter, "庫存上拋")
Rel(buy,itemCenter,"商品信息查詢")
Rel(user,orderPlatform,"提交訂單")
Rel(buy,priceCenter,"價格查詢")
Rel(orderPlatform,InventoryCenter,"扣減庫存")
Rel(InventoryCenter, itemCenter, "查詢商品sku")
Rel(priceCenter,itemCenter,"查詢商品sku")
Rel(user,buy,"用戶瀏覽")
@enduml